import { getDatabase } from "@netlify/database";
import type { Config, Context } from "@netlify/functions";
import { getSessionUser, unauthorized } from "./_auth.mts";

const asNumber = (value: unknown) => Number(value ?? 0) || 0;
const dateOrNull = (value: unknown) => value ? String(value) : null;
const text = (value: unknown) => value == null ? "" : String(value);

async function readState() {
  const db = getDatabase();
  const [clients, products, sales, lines, payments, expenses, entries, quotes, quoteLines, meta] = await Promise.all([
    db.sql`SELECT * FROM clients ORDER BY name`, db.sql`SELECT * FROM products ORDER BY name, color, size`, db.sql`SELECT * FROM sales ORDER BY sale_date DESC, id DESC`, db.sql`SELECT * FROM sale_lines ORDER BY sale_id, line_no`, db.sql`SELECT * FROM payments ORDER BY payment_date, id`, db.sql`SELECT * FROM expenses ORDER BY expense_date DESC, id DESC`, db.sql`SELECT * FROM entries ORDER BY entry_date DESC, id DESC`, db.sql`SELECT * FROM quotes ORDER BY quote_date DESC, id DESC`, db.sql`SELECT * FROM quote_lines ORDER BY quote_id, line_no`, db.sql`SELECT revision, updated_at FROM app_meta WHERE id = 1`,
  ]);
  const saleLines = new Map<string, any[]>(); for (const l of lines) { const list = saleLines.get(l.sale_id) ?? []; list.push({ productId:l.product_id, product:l.product, qty:l.qty, unitPrice:asNumber(l.unit_price), unitCost:asNumber(l.unit_cost), size:l.size??"", color:l.color??"", category:l.category??"" }); saleLines.set(l.sale_id,list); }
  const salePayments = new Map<string, any[]>(); for (const p of payments) { const list=salePayments.get(p.sale_id)??[]; list.push({id:p.id,date:p.payment_date,amount:asNumber(p.amount),method:p.method??"Pix",terms:p.terms??"",note:p.note??""}); salePayments.set(p.sale_id,list); }
  const qLines = new Map<string, any[]>(); for (const l of quoteLines) { const list=qLines.get(l.quote_id)??[]; list.push({productId:l.product_id,product:l.product,qty:l.qty,unitPrice:asNumber(l.unit_price),unitCost:asNumber(l.unit_cost),size:l.size??"",color:l.color??"",category:l.category??""}); qLines.set(l.quote_id,list); }
  return { version:10, revision:Number(meta[0]?.revision??0), updatedAt:meta[0]?.updated_at??null,
    clients:clients.map((c:any)=>({id:c.id,name:c.name,phone:c.phone??"",city:c.city??"",birthday:c.birthday,source:c.source??"",status:c.status??"Ativo",totalSpent:asNumber(c.total_spent),lastPurchase:c.last_purchase,notes:c.notes??""})),
    products:products.map((p:any)=>({id:p.id,code:p.code??"",name:p.name,category:p.category??"",size:p.size??"",color:p.color??"",stock:Number(p.stock??0),price:asNumber(p.price),cost:asNumber(p.cost)})),
    sales:sales.map((s:any)=>({id:s.id,client:s.client,clientId:s.client_id,date:s.sale_date,subtotal:asNumber(s.subtotal),discountType:s.discount_type??"none",discountValue:asNumber(s.discount_value),discountAmount:asNumber(s.discount_amount),total:asNumber(s.total),items:Number(s.items??0),payment:s.payment??"Pix",paymentTerms:s.payment_terms??"",condition:s.condition??"full",dueDate:s.due_date??"",lines:saleLines.get(s.id)??[],payments:salePayments.get(s.id)??[]})),
    expenses:expenses.map((e:any)=>({id:e.id,date:e.expense_date,description:e.description,category:e.category??"Operacional",amount:asNumber(e.amount)})),
    entries:entries.map((e:any)=>({id:e.id,date:e.entry_date,productId:e.product_id,productCode:e.product_code??"",productName:e.product_name,qty:Number(e.qty??0),unitCost:asNumber(e.unit_cost),totalCost:asNumber(e.total_cost),previousCost:asNumber(e.previous_cost),newCost:asNumber(e.new_cost)})),
    quotes:quotes.map((q:any)=>({id:q.id,client:q.client,clientId:q.client_id,date:q.quote_date,subtotal:asNumber(q.subtotal),discountType:q.discount_type??"none",discountValue:asNumber(q.discount_value),discountAmount:asNumber(q.discount_amount),total:asNumber(q.total),items:Number(q.items??0),payment:q.payment??"Pix",paymentTerms:q.payment_terms??"",condition:q.condition??"full",dueDate:q.due_date??"",status:q.status??"Ativo",lines:qLines.get(q.id)??[]})) };
}

function sanitizeSellerState(state:any){ return {...state, products:(state.products??[]).map((p:any)=>({...p,cost:0})), sales:(state.sales??[]).map((s:any)=>({...s,lines:(s.lines??[]).map((l:any)=>({...l,unitCost:0}))})), quotes:(state.quotes??[]).map((q:any)=>({...q,lines:(q.lines??[]).map((l:any)=>({...l,unitCost:0}))})), expenses:[], entries:[]}; }
function soldByProduct(sales:any[]){ const totals=new Map<string,number>(); for(const sale of sales??[]) for(const line of sale.lines??[]){const id=String(line.productId??""); if(id) totals.set(id,(totals.get(id)??0)+Math.max(0,Number(line.qty)||0));} return totals; }
function secureSellerWrite(incoming:any,current:any){
  const productMap=new Map((current.products??[]).map((p:any)=>[String(p.id),p])); const oldSalesMap=new Map((current.sales??[]).map((s:any)=>[String(s.id),s])); const oldSold=soldByProduct(current.sales??[]),newSold=soldByProduct(incoming.sales??[]);
  const products=(current.products??[]).map((p:any)=>{const id=String(p.id); const nextStock=Math.round((Number(p.stock)+(oldSold.get(id)??0)-(newSold.get(id)??0))*1000)/1000; if(nextStock<-.0001) throw Object.assign(new Error("INSUFFICIENT_STOCK"),{code:"INSUFFICIENT_STOCK",product:p.name}); return {...p,stock:Math.max(0,nextStock)};});
  const sales=(incoming.sales??[]).map((s:any)=>{const oldSale:any=oldSalesMap.get(String(s.id)); const lines=(s.lines??[]).map((l:any)=>{const product:any=productMap.get(String(l.productId)); if(!product) throw Object.assign(new Error("UNKNOWN_PRODUCT"),{code:"UNKNOWN_PRODUCT"}); const previous=(oldSale?.lines??[]).find((x:any)=>String(x.productId)===String(l.productId)); return {...l,product:product.name,size:product.size,color:product.color,category:product.category,unitPrice:previous?asNumber(previous.unitPrice):asNumber(product.price),unitCost:previous?asNumber(previous.unitCost):asNumber(product.cost),qty:Math.max(1,Math.floor(Number(l.qty)||1))};}); const subtotal=lines.reduce((sum:number,l:any)=>sum+asNumber(l.unitPrice)*Number(l.qty),0),discountAmount=Math.max(0,Math.min(subtotal,asNumber(s.discountAmount))); return {...s,lines,subtotal,discountAmount,total:subtotal-discountAmount,items:lines.reduce((a:number,l:any)=>a+Number(l.qty),0)};});
  const totals=new Map<string,{total:number;last:string}>(); for(const sale of sales){const cid=String(sale.clientId??""); if(!cid) continue; const prev=totals.get(cid)??{total:0,last:""}; prev.total+=asNumber(sale.total); if(String(sale.date??"")>prev.last) prev.last=String(sale.date??""); totals.set(cid,prev);} const clients=(incoming.clients??[]).map((c:any)=>{const t=totals.get(String(c.id))??{total:0,last:""}; return {...c,totalSpent:t.total,lastPurchase:t.last,status:t.total>=1000?"VIP":(c.status==="Reativar"?"Reativar":"Ativo")};});
  const quotes=(incoming.quotes??[]).map((q:any)=>{const lines=(q.lines??[]).map((l:any)=>{const product:any=productMap.get(String(l.productId)); if(!product) throw Object.assign(new Error("UNKNOWN_PRODUCT"),{code:"UNKNOWN_PRODUCT"}); return {...l,product:product.name,size:product.size,color:product.color,category:product.category,unitPrice:asNumber(product.price),unitCost:asNumber(product.cost),qty:Math.max(1,Math.floor(Number(l.qty)||1))};}); const subtotal=lines.reduce((sum:number,l:any)=>sum+asNumber(l.unitPrice)*Number(l.qty),0),discountAmount=Math.max(0,Math.min(subtotal,asNumber(q.discountAmount))); return {...q,lines,subtotal,discountAmount,total:subtotal-discountAmount,items:lines.reduce((a:number,l:any)=>a+Number(l.qty),0)};});
  return {...current,clients,sales,quotes,products,expenses:current.expenses,entries:current.entries};
}

async function replaceState(state:any,expectedRevision:number|null){ const db=getDatabase(); const client=await db.pool.connect(); try{ await client.query("BEGIN"); const currentMeta=await client.query("SELECT revision FROM app_meta WHERE id = 1 FOR UPDATE"); const currentRevision=Number(currentMeta.rows[0]?.revision??0); if(expectedRevision!==null&&Number.isFinite(expectedRevision)&&currentRevision!==expectedRevision){await client.query("ROLLBACK"); const conflict:any=new Error("REVISION_CONFLICT"); conflict.code="REVISION_CONFLICT"; throw conflict;} await client.query("DELETE FROM payments"); await client.query("DELETE FROM sale_lines"); await client.query("DELETE FROM sales"); await client.query("DELETE FROM quote_lines"); await client.query("DELETE FROM quotes"); await client.query("DELETE FROM entries"); await client.query("DELETE FROM expenses"); await client.query("DELETE FROM products"); await client.query("DELETE FROM clients");
  for(const c of state.clients??[]) await client.query(`INSERT INTO clients (id,name,phone,city,birthday,source,status,total_spent,last_purchase,notes) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)`,[text(c.id),text(c.name),text(c.phone),text(c.city),dateOrNull(c.birthday),text(c.source),text(c.status||"Ativo"),asNumber(c.totalSpent),dateOrNull(c.lastPurchase),text(c.notes)]);
  for(const p of state.products??[]) await client.query(`INSERT INTO products (id,code,name,category,size,color,stock,price,cost) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9)`,[text(p.id),text(p.code),text(p.name),text(p.category),text(p.size),text(p.color),Number(p.stock??0),asNumber(p.price),asNumber(p.cost)]);
  for(const s of state.sales??[]){await client.query(`INSERT INTO sales (id,client,client_id,sale_date,subtotal,discount_type,discount_value,discount_amount,total,items,payment,payment_terms,condition,due_date) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14)`,[text(s.id),text(s.client),s.clientId||null,dateOrNull(s.date),asNumber(s.subtotal??s.total),text(s.discountType||"none"),asNumber(s.discountValue),asNumber(s.discountAmount),asNumber(s.total),Number(s.items??(s.lines?.length??0)),text(s.payment||"Pix"),text(s.paymentTerms),text(s.condition||"full"),dateOrNull(s.dueDate)]); let n=0; for(const l of s.lines??[]) await client.query(`INSERT INTO sale_lines (sale_id,line_no,product_id,product,qty,unit_price,unit_cost,size,color,category) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)`,[text(s.id),n++,l.productId||null,text(l.product),Number(l.qty??1),asNumber(l.unitPrice),asNumber(l.unitCost),text(l.size),text(l.color),text(l.category)]); for(const p of s.payments??[]) await client.query(`INSERT INTO payments (id,sale_id,payment_date,amount,method,terms,note) VALUES ($1,$2,$3,$4,$5,$6,$7)`,[text(p.id),text(s.id),dateOrNull(p.date||s.date),asNumber(p.amount),text(p.method||"Pix"),text(p.terms),text(p.note)]);}
  for(const e of state.expenses??[]) await client.query(`INSERT INTO expenses (id,expense_date,description,category,amount) VALUES ($1,$2,$3,$4,$5)`,[text(e.id),dateOrNull(e.date),text(e.description),text(e.category||"Operacional"),asNumber(e.amount)]);
  for(const e of state.entries??[]) await client.query(`INSERT INTO entries (id,entry_date,product_id,product_code,product_name,qty,unit_cost,total_cost,previous_cost,new_cost) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)`,[text(e.id),dateOrNull(e.date),e.productId||null,text(e.productCode),text(e.productName),Number(e.qty??0),asNumber(e.unitCost),asNumber(e.totalCost),asNumber(e.previousCost),asNumber(e.newCost??e.unitCost)]);
  for(const q of state.quotes??[]){await client.query(`INSERT INTO quotes (id,client,client_id,quote_date,subtotal,discount_type,discount_value,discount_amount,total,items,payment,payment_terms,condition,due_date,status) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15)`,[text(q.id),text(q.client),q.clientId||null,dateOrNull(q.date),asNumber(q.subtotal??q.total),text(q.discountType||"none"),asNumber(q.discountValue),asNumber(q.discountAmount),asNumber(q.total),Number(q.items??(q.lines?.length??0)),text(q.payment||"Pix"),text(q.paymentTerms),text(q.condition||"full"),dateOrNull(q.dueDate),text(q.status||"Ativo")]); let n=0; for(const l of q.lines??[]) await client.query(`INSERT INTO quote_lines (quote_id,line_no,product_id,product,qty,unit_price,unit_cost,size,color,category) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)`,[text(q.id),n++,l.productId||null,text(l.product),Number(l.qty??1),asNumber(l.unitPrice),asNumber(l.unitCost),text(l.size),text(l.color),text(l.category)]);}
  const result=await client.query("UPDATE app_meta SET revision = revision + 1, updated_at = NOW() WHERE id = 1 RETURNING revision, updated_at"); await client.query("COMMIT"); return result.rows[0]; }catch(error){try{await client.query("ROLLBACK")}catch{} throw error;}finally{client.release();}}

export default async(req:Request,_context:Context)=>{try{const user=await getSessionUser(req); if(!user)return unauthorized(); if(req.method==="GET"){const state=await readState(); return Response.json(user.role==="seller"?sanitizeSellerState(state):state,{headers:{"Cache-Control":"no-store"}});} if(req.method==="PUT"){const payload=await req.json(); const incoming=payload?.state??payload; const expectedRevision=payload?.expectedRevision==null?null:Number(payload.expectedRevision); if(!incoming||!Array.isArray(incoming.clients)||!Array.isArray(incoming.products)||!Array.isArray(incoming.sales))return Response.json({error:"Invalid state"},{status:400}); const state=user.role==="seller"?secureSellerWrite(incoming,await readState()):incoming; const meta=await replaceState(state,expectedRevision); return Response.json({ok:true,revision:Number(meta.revision),updatedAt:meta.updated_at});} return new Response("Method Not Allowed",{status:405});}catch(error:any){if(error?.code==="REVISION_CONFLICT"||error?.message==="REVISION_CONFLICT")return Response.json({error:"Revision conflict"},{status:409}); if(error?.code==="INSUFFICIENT_STOCK")return Response.json({error:"Insufficient stock",product:error.product},{status:409}); if(error?.code==="UNKNOWN_PRODUCT")return Response.json({error:"Unknown product"},{status:400}); console.error(error); return Response.json({error:"Database operation failed"},{status:500});}};
export const config: Config={path:"/api/state"};
